#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("sample.Resource", IsApplication=true)]

namespace sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MPDC.Android.CircularProgress.Resource.Attribute.donutProgressStyle = global::sample.Resource.Attribute.donutProgressStyle;
			global::MPDC.Android.CircularProgress.Resource.Attribute.donut_background_color = global::sample.Resource.Attribute.donut_background_color;
			global::MPDC.Android.CircularProgress.Resource.Attribute.donut_circle_starting_degree = global::sample.Resource.Attribute.donut_circle_starting_degree;
			global::MPDC.Android.CircularProgress.Resource.Attribute.donut_finished_color = global::sample.Resource.Attribute.donut_finished_color;
			global::MPDC.Android.CircularProgress.Resource.Attribute.donut_finished_stroke_width = global::sample.Resource.Attribute.donut_finished_stroke_width;
			global::MPDC.Android.CircularProgress.Resource.Attribute.donut_inner_bottom_text = global::sample.Resource.Attribute.donut_inner_bottom_text;
			global::MPDC.Android.CircularProgress.Resource.Attribute.donut_inner_bottom_text_color = global::sample.Resource.Attribute.donut_inner_bottom_text_color;
			global::MPDC.Android.CircularProgress.Resource.Attribute.donut_inner_bottom_text_size = global::sample.Resource.Attribute.donut_inner_bottom_text_size;
			global::MPDC.Android.CircularProgress.Resource.Attribute.donut_inner_drawable = global::sample.Resource.Attribute.donut_inner_drawable;
			global::MPDC.Android.CircularProgress.Resource.Attribute.donut_max = global::sample.Resource.Attribute.donut_max;
			global::MPDC.Android.CircularProgress.Resource.Attribute.donut_prefix_text = global::sample.Resource.Attribute.donut_prefix_text;
			global::MPDC.Android.CircularProgress.Resource.Attribute.donut_progress = global::sample.Resource.Attribute.donut_progress;
			global::MPDC.Android.CircularProgress.Resource.Attribute.donut_show_text = global::sample.Resource.Attribute.donut_show_text;
			global::MPDC.Android.CircularProgress.Resource.Attribute.donut_suffix_text = global::sample.Resource.Attribute.donut_suffix_text;
			global::MPDC.Android.CircularProgress.Resource.Attribute.donut_text = global::sample.Resource.Attribute.donut_text;
			global::MPDC.Android.CircularProgress.Resource.Attribute.donut_text_color = global::sample.Resource.Attribute.donut_text_color;
			global::MPDC.Android.CircularProgress.Resource.Attribute.donut_text_size = global::sample.Resource.Attribute.donut_text_size;
			global::MPDC.Android.CircularProgress.Resource.Attribute.donut_unfinished_color = global::sample.Resource.Attribute.donut_unfinished_color;
			global::MPDC.Android.CircularProgress.Resource.Attribute.donut_unfinished_stroke_width = global::sample.Resource.Attribute.donut_unfinished_stroke_width;
			global::MPDC.Android.CircularProgress.Resource.String.library_name = global::sample.Resource.String.library_name;
			global::MPDC.Android.CircularProgress.Resource.Styleable.DonutProgress = global::sample.Resource.Styleable.DonutProgress;
			global::MPDC.Android.CircularProgress.Resource.Styleable.DonutProgress_donut_background_color = global::sample.Resource.Styleable.DonutProgress_donut_background_color;
			global::MPDC.Android.CircularProgress.Resource.Styleable.DonutProgress_donut_circle_starting_degree = global::sample.Resource.Styleable.DonutProgress_donut_circle_starting_degree;
			global::MPDC.Android.CircularProgress.Resource.Styleable.DonutProgress_donut_finished_color = global::sample.Resource.Styleable.DonutProgress_donut_finished_color;
			global::MPDC.Android.CircularProgress.Resource.Styleable.DonutProgress_donut_finished_stroke_width = global::sample.Resource.Styleable.DonutProgress_donut_finished_stroke_width;
			global::MPDC.Android.CircularProgress.Resource.Styleable.DonutProgress_donut_inner_bottom_text = global::sample.Resource.Styleable.DonutProgress_donut_inner_bottom_text;
			global::MPDC.Android.CircularProgress.Resource.Styleable.DonutProgress_donut_inner_bottom_text_color = global::sample.Resource.Styleable.DonutProgress_donut_inner_bottom_text_color;
			global::MPDC.Android.CircularProgress.Resource.Styleable.DonutProgress_donut_inner_bottom_text_size = global::sample.Resource.Styleable.DonutProgress_donut_inner_bottom_text_size;
			global::MPDC.Android.CircularProgress.Resource.Styleable.DonutProgress_donut_inner_drawable = global::sample.Resource.Styleable.DonutProgress_donut_inner_drawable;
			global::MPDC.Android.CircularProgress.Resource.Styleable.DonutProgress_donut_max = global::sample.Resource.Styleable.DonutProgress_donut_max;
			global::MPDC.Android.CircularProgress.Resource.Styleable.DonutProgress_donut_prefix_text = global::sample.Resource.Styleable.DonutProgress_donut_prefix_text;
			global::MPDC.Android.CircularProgress.Resource.Styleable.DonutProgress_donut_progress = global::sample.Resource.Styleable.DonutProgress_donut_progress;
			global::MPDC.Android.CircularProgress.Resource.Styleable.DonutProgress_donut_show_text = global::sample.Resource.Styleable.DonutProgress_donut_show_text;
			global::MPDC.Android.CircularProgress.Resource.Styleable.DonutProgress_donut_suffix_text = global::sample.Resource.Styleable.DonutProgress_donut_suffix_text;
			global::MPDC.Android.CircularProgress.Resource.Styleable.DonutProgress_donut_text = global::sample.Resource.Styleable.DonutProgress_donut_text;
			global::MPDC.Android.CircularProgress.Resource.Styleable.DonutProgress_donut_text_color = global::sample.Resource.Styleable.DonutProgress_donut_text_color;
			global::MPDC.Android.CircularProgress.Resource.Styleable.DonutProgress_donut_text_size = global::sample.Resource.Styleable.DonutProgress_donut_text_size;
			global::MPDC.Android.CircularProgress.Resource.Styleable.DonutProgress_donut_unfinished_color = global::sample.Resource.Styleable.DonutProgress_donut_unfinished_color;
			global::MPDC.Android.CircularProgress.Resource.Styleable.DonutProgress_donut_unfinished_stroke_width = global::sample.Resource.Styleable.DonutProgress_donut_unfinished_stroke_width;
			global::MPDC.Android.CircularProgress.Resource.Styleable.Themes = global::sample.Resource.Styleable.Themes;
			global::MPDC.Android.CircularProgress.Resource.Styleable.Themes_donutProgressStyle = global::sample.Resource.Styleable.Themes_donutProgressStyle;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010012
			public const int donutProgressStyle = 2130771986;
			
			// aapt resource value: 0x7f01000b
			public const int donut_background_color = 2130771979;
			
			// aapt resource value: 0x7f01000f
			public const int donut_circle_starting_degree = 2130771983;
			
			// aapt resource value: 0x7f010003
			public const int donut_finished_color = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int donut_finished_stroke_width = 2130771972;
			
			// aapt resource value: 0x7f01000c
			public const int donut_inner_bottom_text = 2130771980;
			
			// aapt resource value: 0x7f01000e
			public const int donut_inner_bottom_text_color = 2130771982;
			
			// aapt resource value: 0x7f01000d
			public const int donut_inner_bottom_text_size = 2130771981;
			
			// aapt resource value: 0x7f010011
			public const int donut_inner_drawable = 2130771985;
			
			// aapt resource value: 0x7f010001
			public const int donut_max = 2130771969;
			
			// aapt resource value: 0x7f010008
			public const int donut_prefix_text = 2130771976;
			
			// aapt resource value: 0x7f010000
			public const int donut_progress = 2130771968;
			
			// aapt resource value: 0x7f010010
			public const int donut_show_text = 2130771984;
			
			// aapt resource value: 0x7f010009
			public const int donut_suffix_text = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int donut_text = 2130771978;
			
			// aapt resource value: 0x7f010007
			public const int donut_text_color = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int donut_text_size = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int donut_unfinished_color = 2130771970;
			
			// aapt resource value: 0x7f010005
			public const int donut_unfinished_stroke_width = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int donut_progress = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int myButton = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] DonutProgress = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985};
			
			// aapt resource value: 11
			public const int DonutProgress_donut_background_color = 11;
			
			// aapt resource value: 15
			public const int DonutProgress_donut_circle_starting_degree = 15;
			
			// aapt resource value: 3
			public const int DonutProgress_donut_finished_color = 3;
			
			// aapt resource value: 4
			public const int DonutProgress_donut_finished_stroke_width = 4;
			
			// aapt resource value: 12
			public const int DonutProgress_donut_inner_bottom_text = 12;
			
			// aapt resource value: 14
			public const int DonutProgress_donut_inner_bottom_text_color = 14;
			
			// aapt resource value: 13
			public const int DonutProgress_donut_inner_bottom_text_size = 13;
			
			// aapt resource value: 17
			public const int DonutProgress_donut_inner_drawable = 17;
			
			// aapt resource value: 1
			public const int DonutProgress_donut_max = 1;
			
			// aapt resource value: 8
			public const int DonutProgress_donut_prefix_text = 8;
			
			// aapt resource value: 0
			public const int DonutProgress_donut_progress = 0;
			
			// aapt resource value: 16
			public const int DonutProgress_donut_show_text = 16;
			
			// aapt resource value: 9
			public const int DonutProgress_donut_suffix_text = 9;
			
			// aapt resource value: 10
			public const int DonutProgress_donut_text = 10;
			
			// aapt resource value: 7
			public const int DonutProgress_donut_text_color = 7;
			
			// aapt resource value: 6
			public const int DonutProgress_donut_text_size = 6;
			
			// aapt resource value: 2
			public const int DonutProgress_donut_unfinished_color = 2;
			
			// aapt resource value: 5
			public const int DonutProgress_donut_unfinished_stroke_width = 5;
			
			public static int[] Themes = new int[] {
					2130771986};
			
			// aapt resource value: 0
			public const int Themes_donutProgressStyle = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
