#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MPDC.Android.CircularProgress.Resource", IsApplication=false)]

namespace MPDC.Android.CircularProgress
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010012
			public static int donutProgressStyle = 2130771986;
			
			// aapt resource value: 0x7f01000b
			public static int donut_background_color = 2130771979;
			
			// aapt resource value: 0x7f01000f
			public static int donut_circle_starting_degree = 2130771983;
			
			// aapt resource value: 0x7f010003
			public static int donut_finished_color = 2130771971;
			
			// aapt resource value: 0x7f010004
			public static int donut_finished_stroke_width = 2130771972;
			
			// aapt resource value: 0x7f01000c
			public static int donut_inner_bottom_text = 2130771980;
			
			// aapt resource value: 0x7f01000e
			public static int donut_inner_bottom_text_color = 2130771982;
			
			// aapt resource value: 0x7f01000d
			public static int donut_inner_bottom_text_size = 2130771981;
			
			// aapt resource value: 0x7f010011
			public static int donut_inner_drawable = 2130771985;
			
			// aapt resource value: 0x7f010001
			public static int donut_max = 2130771969;
			
			// aapt resource value: 0x7f010008
			public static int donut_prefix_text = 2130771976;
			
			// aapt resource value: 0x7f010000
			public static int donut_progress = 2130771968;
			
			// aapt resource value: 0x7f010010
			public static int donut_show_text = 2130771984;
			
			// aapt resource value: 0x7f010009
			public static int donut_suffix_text = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public static int donut_text = 2130771978;
			
			// aapt resource value: 0x7f010007
			public static int donut_text_color = 2130771975;
			
			// aapt resource value: 0x7f010006
			public static int donut_text_size = 2130771974;
			
			// aapt resource value: 0x7f010002
			public static int donut_unfinished_color = 2130771970;
			
			// aapt resource value: 0x7f010005
			public static int donut_unfinished_stroke_width = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f020000
			public static int library_name = 2130837504;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] DonutProgress = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985};
			
			// aapt resource value: 11
			public static int DonutProgress_donut_background_color = 11;
			
			// aapt resource value: 15
			public static int DonutProgress_donut_circle_starting_degree = 15;
			
			// aapt resource value: 3
			public static int DonutProgress_donut_finished_color = 3;
			
			// aapt resource value: 4
			public static int DonutProgress_donut_finished_stroke_width = 4;
			
			// aapt resource value: 12
			public static int DonutProgress_donut_inner_bottom_text = 12;
			
			// aapt resource value: 14
			public static int DonutProgress_donut_inner_bottom_text_color = 14;
			
			// aapt resource value: 13
			public static int DonutProgress_donut_inner_bottom_text_size = 13;
			
			// aapt resource value: 17
			public static int DonutProgress_donut_inner_drawable = 17;
			
			// aapt resource value: 1
			public static int DonutProgress_donut_max = 1;
			
			// aapt resource value: 8
			public static int DonutProgress_donut_prefix_text = 8;
			
			// aapt resource value: 0
			public static int DonutProgress_donut_progress = 0;
			
			// aapt resource value: 16
			public static int DonutProgress_donut_show_text = 16;
			
			// aapt resource value: 9
			public static int DonutProgress_donut_suffix_text = 9;
			
			// aapt resource value: 10
			public static int DonutProgress_donut_text = 10;
			
			// aapt resource value: 7
			public static int DonutProgress_donut_text_color = 7;
			
			// aapt resource value: 6
			public static int DonutProgress_donut_text_size = 6;
			
			// aapt resource value: 2
			public static int DonutProgress_donut_unfinished_color = 2;
			
			// aapt resource value: 5
			public static int DonutProgress_donut_unfinished_stroke_width = 5;
			
			public static int[] Themes = new int[] {
					2130771986};
			
			// aapt resource value: 0
			public static int Themes_donutProgressStyle = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
